### ISSUE TITLE
小程序添加订单报错

### ISSUE THREAD

**Issue by im-zhangxi** [dspurl/dsshop#12]
![image](https://user-images.githubusercontent.com/18593080/95827076-d7e68980-0d65-11eb-9837-17351e987d55.png)

**Comment by Caisen1988** [comment]
我之前也遇到过，
![image](https://user-images.githubusercontent.com/11453160/95828713-e766d200-0d67-11eb-980f-659df3426aaa.png)

**Comment by dspurl** [comment]
@im-zhangxi 使用的版本是多少？直接购买是否有这种情况？是否是首次创建地址后发生的问题？因为你的实付款并未计算正确，最新版本之前是存在这个BUG的，因首次添加收货地址并未同步数据，导致实付款并未计算正确

**Comment by im-zhangxi** [comment]
@dspurl     使用的 你的  小程序演示版本.... 还没正式使用.... 本身只是想看看 功能

**Comment by dspurl** [comment]
@im-zhangxi 嗯，确实，演示版有这个问题，可能没有更新的问题导致的，已经重新打包，审核过应该就可以正常了

**Comment by im-zhangxi** [comment]
@dspurl  多谢
