### ISSUE TITLE
laradock nginx 404

### ISSUE THREAD

**Issue by carsonlaw** [dspurl/dsshop#143]
nginx/sites/****.conf 如下：

server {

    listen 80;
    listen [::]:80;

    # For https
    # listen 443 ssl;
    # listen [::]:443 ssl ipv6only=on;
    # ssl_certificate /etc/nginx/ssl/default.crt;
    # ssl_certificate_key /etc/nginx/ssl/default.key;

    server_name ****.com;
    root /var/www/dsshop/api/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }
    。。。。。。

官方文档只针对windows404说了配置，但是我的centos
非常感谢

**Comment by carsonlaw** [comment]
非常感谢，但是配置了还是不行，sites下面的几个配置都试过了，感觉不像是这个配置的问题

**Comment by carsonlaw** [comment]
就是php的配置有问题，我把
`location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }`
注释掉，就可以访问静态文件了，被laradock搞死了

**Comment by dspurl** [comment]
laradock按正常流程搭建的话，php是不会有问题的才对，你先装个laravel官方版本看下，如果能正常搭建起来了，再去安装dsshop

**Comment by carsonlaw** [comment]
我把注释的放开，竟然有可以了，莫名其妙的。
现在我下载了最新的XH3.1.7，导入client/DSShop识别不了是uniapp，识别是web项目不能生成小程序和app等
是因为什么原因呢，感谢

**Comment by dspurl** [comment]
用打开目录，选择`client/DSShop`，然后安装相应依赖，选择`APP.vue`再运行就可以了

**Comment by dspurl** [comment]
我看了下，master分支没有APP.vue，你下install分支吧，或是把install分支的APP.vue复制过去

**Comment by carsonlaw** [comment]
install分支是可以的，但是接口都401了，已经配置了secret了，请求里也有 apply-secret: base64:xduEeT/C6pZmbmr5HOvHxy+6zsPl5BZFpEZN65/tF1w=

**Comment by dspurl** [comment]
install不用导入，直接就能用，具体看文档中的傻瓜式安装
代码安装的话，我记得不需要改` apply-secret`，默认就已经填写正确的密钥了
