### ISSUE TITLE
API密钥错误

### ISSUE THREAD

**Issue by WCNJasonZheng** [dspurl/dsshop#15]
![image](https://user-images.githubusercontent.com/67033655/97251902-c3b18a80-1843-11eb-8f55-5c93cf7c85b4.png)

你好，请问我App.vue这样设置正确吗，h5一直提示API密钥错误

**Comment by dspurl** [comment]
@WCNJasonZheng 你密钥修改错位置了，新版应该是52行左右
![image](https://user-images.githubusercontent.com/49799121/97253425-556ec700-1847-11eb-8216-c880b340ac06.png)

**Comment by WCNJasonZheng** [comment]
@dspurl 你好，我在52行修改了密钥，仍然会出现报错

**Comment by WCNJasonZheng** [comment]
![image](https://user-images.githubusercontent.com/67033655/97259309-7c33fa00-1855-11eb-9613-3d7cade2bca6.png)

**Comment by dspurl** [comment]
@WCNJasonZheng 清下缓存，或将App.vue第9行的`uni.clearStorage()`注释打开，然后刷新下页面，在chrome浏览器按F12或在HBuilder X的内置浏览器“显示开发者工具”，查看Network实际调用接口传的Headers头中apply-secret的值是否是你填写的信息
![image](https://user-images.githubusercontent.com/49799121/97262539-067f5c80-185c-11eb-8761-5fd211e89da6.png)
![image](https://user-images.githubusercontent.com/49799121/97262584-2282fe00-185c-11eb-9afd-0cbac9d30f59.png)

**Comment by dspurl** [comment]
@WCNJasonZheng 清掉缓存后，记得注释掉`uni.clearStorage()`
