### ISSUE TITLE
订单支付成功是提示： 错误20001，请联系管理员

### ISSUE THREAD

**Issue by sayhei** [dspurl/dsshop#155]
今天想去完整走一走小程序的功能，发现遇到各种问题，这整个系统能够完整的运行么？还是我操作方式不对？

**Comment by dspurl** [comment]
请体验线上演示效果，如果线上可以正常跑通，本地不行，即本地操作问题，该项目版本更新迭代比较快，它是一种解决方案，非直接可用，如需用于商用，请自行二次开发

**Comment by sayhei** [comment]
线上目前应该是沙盒环境，我用的非沙盒环境，支付完成之后购物车没清空
