### ISSUE TITLE
建议将所有数据库建表文件中的charset、engine、collation属性都去掉，或者改成utf8mb4

### ISSUE THREAD

**Issue by czhou** [dspurl/dsshop#163]
现在都是写死的：
`$table->charset = 'utf8';`
`$table->engine = 'InnoDB';`
`$table->collation = 'utf8_general_ci';`
utf8不能存储emoji字符，会给第三方登录复用用户名造成麻烦（很多微信用户名都带有emoji字符）
InnoDB都是标配了，完全不必写进来。
总之这样写死的配置很不灵活，用户没办法在建库的时候指定默认字符集（指定了也会被这里的代码覆盖），所以要么去掉让用户自己在create database的时候指定，要么改成：
`$table->charset = 'utf8mb4';`
`$table->engine = 'InnoDB';`
`$table->collation = 'utf8mb4_unicode_ci';`
用utf8mb4以便存储更多字符。

**Comment by dspurl** [comment]
可以

**Comment by czhou** [comment]
ok，稍后我提交个PR。
