### ISSUE TITLE
客户端 401 密匙错误

### ISSUE THREAD

**Issue by zhiliangxie** [dspurl/dsshop#170]
修改client里面的 uitils.env 密匙跟api  .env 一样但是依然提示401 密匙错误

![image](https://user-images.githubusercontent.com/35464491/122737342-3bc03b00-d281-11eb-9234-e4e755c8c134.png)

**Comment by dspurl** [comment]
前端密钥需要在.env配置`PROJECT_KEY`，而非`APP_KEY`
参考配置说明：https://dswjcms_purl.gitee.io/dsshop/guide/basic.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by zhiliangxie** [comment]
谢谢，已解决！
