### ISSUE TITLE
感谢dsshop的帮助,提供宝塔一键部署脚本

### ISSUE THREAD

**Issue by AckerPaul** [dspurl/dsshop#173]
望采纳
@dspurl

https://github.com/AckerPaul/btdsshop

**Comment by dspurl** [comment]
感谢，已加入手册https://dspurl.github.io/dsshop/guide/getting-started.html#%E5%9F%BA%E4%BA%8E%E5%AE%9D%E5%A1%94%E5%AE%89%E8%A3%85
