### ISSUE TITLE
为什么安装 window is not defined 呢？

### ISSUE THREAD

**Issue by arvsabert** [dspurl/dsshop#174]
![image](https://user-images.githubusercontent.com/42908592/129471850-fa1be792-ab88-48ff-9f7e-7ecdf2a600dc.png)

uni-app 根据文档 yarn install 安装后 执行 yarn run dev，抛出以下错误：
![image](https://user-images.githubusercontent.com/42908592/129471901-8341973e-af7a-4907-bf8a-752a6312428e.png)
网页错误 为 
![image](https://user-images.githubusercontent.com/42908592/129471925-06e5afc2-4b3c-4cbc-97f6-24d753a3516e.png)
请问这是什么错误啊？

**Comment by dspurl** [comment]
下载`new`分支下的`package-lock.json`，把生成的node_modules删除，然后用npm来安装

**Comment by arvsabert** [comment]
> 下载`new`分支下的`package-lock.json`，把生成的node_modules删除，然后用npm来安装

感谢回复！！！

**Comment by wuyangpi** [comment]
同问呢。。。。
