### ISSUE TITLE
关于性能

### ISSUE THREAD

**Issue by AckerPaul** [dspurl/dsshop#180]
看到已经近期已经完美对接了 passport ;
nuxt方面建议采用https://auth.nuxtjs.org/providers/laravel-passport  为后期vue3做准备
另外数据量过大后 passport 频繁的交换key 对服务器的压力 应该上缓存
https://github.com/overtrue/laravel-passport-cache-token
https://github.com/overtrue/laravel-passport-cache-client
只是建议  再次感谢dsshop

**Comment by dspurl** [comment]
1、nuxt方面我看了下，nuxt给的方法应该是针对客户端凭证授予令牌，然后需要重定向，而项目采用的是密码授权方式的令牌的方法，并不需要重定向，所以并不需要按nuxt的方法去处理。
2、缓存那块，我看了下你给的链接，token缓存和客户端缓存好像并不是针对前后端分离的吧，dsshop项目的客户端是写在.env里的，token可以通过后台配置触发频率，默认为2小时，到期后才会去后台请求刷新令牌；而前端会在请求后端接口的时候判断token失效时间小于5分钟，如果符合才会去请求刷新令牌的，所以我感觉并不需要用到缓存

**Comment by AckerPaul** [comment]
我驳回一下 没仔细看你说的  前端会在请求后端接口的时候判断token失效时间小于5分钟 放在前端去判断时间 那就没问题了

**Comment by dspurl** [comment]
嗯，好的，我给生成的token做下redis缓存处理吧，感觉没有必要再去装两个扩展

**Comment by dspurl** [comment]
我试着给生成的token做缓存，但发现并没有用，因为每次调用登录接口并没有唯一值，如果是拿用户ID来做标识的话，发现调用令牌更新接口时，并无法获取用户ID，于是我尝试用你给的那2个扩展，发现客户端那个是会缓存的，但token那块好像重复调用登录接口，都会往oauth_access_tokens插入最新的数据，所以token缓存那个扩展是无效的

**Comment by dspurl** [comment]
我试着给生成的token做缓存，但发现并没有用，因为每次调用登录接口并没有唯一值，如果是拿用户ID来做唯一标识的话，发现调用令牌更新接口时，接口并无法使用用户ID，所以是无法进行缓存的；于是我尝试用你给的那2个扩展，发现客户端那个是会缓存的，但token那块好像重复调用登录接口，都会往oauth_access_tokens插入最新的数据，所以token缓存那个扩展是无效的

**Comment by AckerPaul** [comment]
你直接使用redis 是需要改写 find() 方法的 插件也是这种思路 只不过 更方便了 参考
https://learnku.com/articles/56579 
都会往oauth_access_tokens插入最新的数据 是否应该根据缓存时间 判断一下去redis 里拿
我本地现在没dsshop 没法验证 我明天看有时间测试一下

**Comment by dspurl** [comment]
嗯，好的，那你测试好后如果是可以缓存的话，我再验证下，如果可以的话再更新上去吧
