### ISSUE TITLE
 docker-compose up -d 报错

### ISSUE THREAD

**Issue by chenboxiaoxiao** [dspurl/dsshop#206]
小白用户，安装环境出错，想问问是为啥？如图：
![image](https://user-images.githubusercontent.com/24404701/155910945-ef236731-1889-44c7-bdf1-471f666aec13.png)

**Comment by dspurl** [comment]
从报错来看的话，可能是163源的问题，不排除linux版本的问题，可根据自己的linux版本去更换适合的源，修改位置`docker/php-fpm/sources.list.stretch`
