### ISSUE TITLE
docker-compose up -d报错

### ISSUE THREAD

**Issue by piggy0915** [dspurl/dsshop#228]
你当前的操作系统(必填)
windows10

你使用的版本(必填)
dsshop v3.0.0

详细描述你的bug(必填)
安装环境时，运行docker-compose up -d，出现错误：
The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.11.dfsg-2) but 1:1.2.11.dfsg-2+deb11u1 is to be installed
E: Unable to correct problems, you have held broken packages.

returned a non-zero code: 100
ERROR: Service 'php' failed to build : Build failed
截图见下：
![image](https://user-images.githubusercontent.com/57304823/167625468-e9c9c652-388a-4e19-9445-c29db8b38880.png)

尝试修改dockfile,在   && apt-get install -y zlib1g-dev \ 前增加 && apt-get install --allow-downgrades -y zlib1g=1:1.2.11.dfsg-2  \
无效果

**Comment by dspurl** [comment]
docker在不同的linux下安装结果会不同的，会导致无法正常安装，如果是线上的话，推荐使用腾讯云的轻量应用服务器Docker CE版；如果是本地的话，可以使用Laradock

**Comment by piggy0915** [comment]
我用laradock再试试看

**Comment by piggy0915** [comment]
解决了,把dockfile中的from php-7.4-fpm换成官方的就通过了

**Comment by wangxilou** [comment]
> 

问一下，修改成什么版本了啊

**Comment by piggy0915** [comment]
> > 
> 
> 问一下，修改成什么版本了啊

from php-7.4-fpm-buster
