### ISSUE TITLE
请问，优惠券插件在哪？另外，微信交流群二维码不可用。

### ISSUE THREAD

**Issue by lurenbeia** [dspurl/dsshop#232]
如题，我在官网产品中心中，只发现了这 8 个插件
![image](https://user-images.githubusercontent.com/49217897/172036143-9bcdce65-cbca-4a56-bd2d-abd5a524f607.png)
自己部署后的项目插件列表中只有 4 个
![image](https://user-images.githubusercontent.com/49217897/172036168-f7138f23-c823-438c-80d9-1321fba6b900.png)
这些中都没有 优惠券 插件。

另外，微信交流群二维码扫码后一直加载中
![7f5d4a285e2a03d18153c3570ca5f8a](https://user-images.githubusercontent.com/49217897/172036368-78c7655b-2649-4fe1-949f-70e7ee078800.jpg)

**Comment by dspurl** [comment]
插件后续会有修改，需要请联系官网客服
