### ISSUE TITLE
添加插件，添加数据表时报错“表注释不带参数的话，请不要用":"”

### ISSUE THREAD

**Issue by tianya520** [dspurl/dsshop#235]
DSSHOP 3.0.1
添加插件=》新建数据表=》
![image](https://user-images.githubusercontent.com/63182212/174968533-3d59c6b2-ed78-4597-b182-75ff39784184.png)
![image](https://user-images.githubusercontent.com/63182212/174968712-6372eccf-0563-4cca-a5a7-5303a62695cb.png)
![image](https://user-images.githubusercontent.com/63182212/174968813-b4b21685-6f6a-4799-aef3-9818449cdc75.png)
如图，注释中并没有添加":"
提交时报错“表注释不带参数的话，请不要用":"

**Comment by dspurl** [comment]
请按提问格式进行提问
