### ISSUE TITLE
接口: Referrer Policy: strict-origin-when-cross-origin

### ISSUE THREAD

**Issue by im-zhangxi** [dspurl/dsshop#43]
![image](https://user-images.githubusercontent.com/18593080/98761746-19279300-2411-11eb-8e59-1a88401d76bc.png)

我发布了h5的版本, 我发现了  Referrer Policy: strict-origin-when-cross-origin 这个错误.  
我简单的认为这是一个跨域问题..

我nginx 设置了 允许跨域.  这时候 所有的接口 都可以访问,. 但是  只有  http://xx.com/api/v1/app/advertising?type=1
是错误的.  别的 都是能正常访问的... 求解决方法

**Comment by im-zhangxi** [comment]
![image](https://user-images.githubusercontent.com/18593080/98761963-889d8280-2411-11eb-9d27-3a1f1fffa2de.png)
我使用postman 模拟请求... 是正常的

**Comment by dspurl** [comment]
@im-zhangxi 只有这一个api显示不出来？点击该报红链接，看下返回值是什么，根据你的错误提示，可能是由于http和https的问题，你可以试着切换成https
![image](https://user-images.githubusercontent.com/49799121/98764343-8be73d00-2416-11eb-8a6d-728f4ba98b3d.png)

**Comment by im-zhangxi** [comment]
@dspurl   https://github.com/dspurl/dsshop/issues/43#issuecomment-725178865  
点击链接 显示这个错误 
![image](https://user-images.githubusercontent.com/18593080/98777499-d7f0ac80-242b-11eb-9e28-a445d79968c7.png)

我目前没有配置https.  但是理论上来说 不应该出现这个问题的...

**Comment by im-zhangxi** [comment]
@im-zhangxi  你可以访问下  http://mall.aiwala.com   看下. 就知道了

**Comment by dspurl** [comment]
@im-zhangxi 我看了下，一切正常
![image](https://user-images.githubusercontent.com/49799121/98778216-f905cd00-242c-11eb-9daf-98f1870dcf2b.png)

**Comment by im-zhangxi** [comment]
@dspurl  那应该是我个人的问题了..  我发现 我的电脑,打开那个接口 就有问题.   我用手机 或者换成别的电脑 都是没有问题的.
