### ISSUE TITLE
分类选择问题bug

### ISSUE THREAD

**Issue by im-zhangxi** [dspurl/dsshop#55]
我build除了 h5 页面 并且部署了..

http://mall.aiwala.com/

![image](https://user-images.githubusercontent.com/18593080/99638774-b3c34a00-2a81-11eb-9b4e-dd5a19994a71.png)
当我点击女鞋之后, 又自动切换到女装了...

**Comment by dspurl** [comment]
@im-zhangxi 已修复，master同步下

**Comment by im-zhangxi** [comment]
多谢 @dspurl
