### ISSUE TITLE
请问考虑加入优惠券功能吗

### ISSUE THREAD

**Issue by ksust** [dspurl/dsshop#6]
请问考虑加入优惠券功能吗，优惠券发方法、领取、使用等

**Comment by dspurl** [comment]
> 请问考虑加入优惠券功能吗，优惠券发方法，领取，使用等

后期会考虑开发的，和商城有关的功能都会慢慢开发出来的，因为现在就我一个人，精力有限，所以版本更新一般会1-5个月发布一次，每次发布都是会开发至少一个新功能上去的
