### ISSUE TITLE
mall商城  分类找不到对应的商品

### ISSUE THREAD

**Issue by im-zhangxi** [dspurl/dsshop#62]
![image](https://user-images.githubusercontent.com/18593080/100496652-946aa200-3190-11eb-96c2-1c8eecf47fe7.png)

![image](https://user-images.githubusercontent.com/18593080/100496660-af3d1680-3190-11eb-8947-30c4a95c5b5d.png)

![image](https://user-images.githubusercontent.com/18593080/100496668-bebc5f80-3190-11eb-90ab-d5aeefa94e2c.png)

测试地址:   http://mall.aiwala.com/

**Comment by im-zhangxi** [comment]
![Uploading image.png…]()

**Comment by im-zhangxi** [comment]
同时 问个问题 :   
![image](https://user-images.githubusercontent.com/18593080/100496696-0347fb00-3191-11eb-9e47-3c899f107341.png)  
为何分类会写死那

![image](https://user-images.githubusercontent.com/18593080/100496701-0e029000-3191-11eb-805d-3a23b049d3ce.png)

**Comment by dspurl** [comment]
分类需要填写三级，左边为一级栏目，然后右边的标题是二级，图片为三级，后台栏目配置也需要按三级配置，第三级才是图片
为什么不把分类做活的问题
该功能可有可无，并不引响正常业务运作，故排在较后面的优化上面，如果你需要实现动态分类，你可以按下面思路整合，然后提交Pull requests
一、后台分类表加个状态（是否前端展示），并只允许三级菜单有此动作
二、前台获取三级菜单中加了状态的列表，然后动态渲染即可实现首页动态菜单的功能
