### ISSUE TITLE
master 环境  购物车商品不回显

### ISSUE THREAD

**Issue by im-zhangxi** [dspurl/dsshop#63]
地址:   http://mall.aiwala.com/

点击  购物车:

![image](https://user-images.githubusercontent.com/18593080/100496874-afd6ac80-3192-11eb-8995-e7206ca267cc.png)

**Comment by dspurl** [comment]
我的->设置->清除缓存
产生原因：本地搭建多个dsshop项目或重新部署dsshop超成的缓存错乱，除了购物车会报红外，我的页面的菜单也会出现布局错乱的问题

**Comment by im-zhangxi** [comment]
好的 多谢
