### ISSUE TITLE
Global版

### ISSUE THREAD

**Issue by marcelowu** [dspurl/dsshop#67]
日后会有paypal 支付插件，email注册，和多语言吗，国外网店

**Comment by marcelowu** [comment]
1.3.1 安装有问题，
1.3.0 统计/使用分析

![Captura de tela de 2020-12-01 03-29-42](https://user-images.githubusercontent.com/30912144/100705288-b7aa7280-3385-11eb-8e5a-7d4e05f1e347.png)

**Comment by dspurl** [comment]
1、多语言项目其实是已经支持的，只是现在没有走多语言的模式而已，后期空下来，会慢慢的支持的，国外前期暂时不考虑吧，翻墙并不方便，所以还是以国内的为主，当然有在海外的开发者加入是最好的
2、1.3.1的问题已经修复，一直想下载测试的，没时间，今天晚上刚测过，确实无法安装，现在已经修复，可以正常访问，但没有一个个功能看，有问题的话，欢迎随时issues
3、统计/分析现在用的是小程序的接口，所以在没有配置小程序的时候是会报错的，后期会慢慢的从小程序中脱离

**Comment by marcelowu** [comment]
明白，很好的一个项目，不支持国外用，有点可惜，你可以看看bagisto https://github.com/bagisto/bagisto

**Comment by dspurl** [comment]
嗯，好的，会考虑支持国际版的

**Comment by marcelowu** [comment]
国际版, GDPR插件不能没有, 欧盟《通用数据保护条例》（GDPR）将于2018年5月25日起适用。该条例将影响适用于GDPR的企业收集和管理其客户及雇员个人数据的方式。根据GDPR，任何在欧盟设立机构的企业或者向欧盟境内提供产品和服务的企业在处理欧盟数据主体的个人数据时都应当遵从该要求。
https://github.com/bagisto/bagisto-gdpr

**Comment by marcelowu** [comment]
https://stripe.com/zh-cn-us/guides/general-data-protection-regulation

**Comment by dspurl** [comment]
https://stripe.com/zh-cn-us/guides/general-data-protection-regulation
这个地址访问不了，有没有墙内的地址？

**Comment by marcelowu** [comment]
![Captura de tela de 2020-12-04 02-17-13](https://user-images.githubusercontent.com/30912144/101124993-ecf9cf00-35d6-11eb-9bb7-f47d43bf300c.png)
![Captura de tela de 2020-12-04 02-17-02](https://user-images.githubusercontent.com/30912144/101124996-f08d5600-35d6-11eb-9195-68819e5a9e63.png)
![Captura de tela de 2020-12-04 02-16-49](https://user-images.githubusercontent.com/30912144/101124998-f3884680-35d6-11eb-9acb-f024c1855531.png)
![Captura de tela de 2020-12-04 02-16-38](https://user-images.githubusercontent.com/30912144/101125004-f5eaa080-35d6-11eb-9180-4d56f6221b17.png)
![Captura de tela de 2020-12-04 02-16-29](https://user-images.githubusercontent.com/30912144/101125011-f84cfa80-35d6-11eb-943f-7dbf8342428a.png)
![Captura de tela de 2020-12-04 02-16-19](https://user-images.githubusercontent.com/30912144/101125018-fb47eb00-35d6-11eb-8e69-1238bb627386.png)
![Captura de tela de 2020-12-04 02-16-08](https://user-images.githubusercontent.com/30912144/101125022-fe42db80-35d6-11eb-997b-a566faf287b5.png)
![Captura de tela de 2020-12-04 02-15-57](https://user-images.githubusercontent.com/30912144/101125029-00a53580-35d7-11eb-8bce-341522932a3c.png)
![Captura de tela de 2020-12-04 02-15-47](https://user-images.githubusercontent.com/30912144/101125035-03a02600-35d7-11eb-82c8-b90346227f67.png)
![Captura de tela de 2020-12-04 02-15-33](https://user-images.githubusercontent.com/30912144/101125040-069b1680-35d7-11eb-9a43-89c62b492ce7.png)
![Captura de tela de 2020-12-04 02-15-12](https://user-images.githubusercontent.com/30912144/101125043-09960700-35d7-11eb-8a87-f7acf31ceab5.png)
![Captura de tela de 2020-12-04 02-14-58](https://user-images.githubusercontent.com/30912144/101125050-0bf86100-35d7-11eb-83d1-a412c14baa87.png)

**Comment by dspurl** [comment]
收到，我看下

**Comment by dspurl** [comment]
我看了一遍，看的云里雾里的...
![image](https://user-images.githubusercontent.com/49799121/101276220-2a807700-37e6-11eb-9e03-273610574598.png)
讲的含糊其词，应该就是和个人隐私有关吧，不能把个人信息(如财务信息、健康信息、营销相关信息等)用于营销所用，这应该是针对运营者来说的吧，和系统好像没有关系哦

**Comment by marcelowu** [comment]
http://www.caict.ac.cn/kxyj/qwfb/ztbg/201905/P020190528556912534746.pdf

![Captura de tela de 2020-12-06 09-08-19](https://user-images.githubusercontent.com/30912144/101279682-a22cb280-37a2-11eb-8994-6693b30aca7b.png)

**Comment by dspurl** [comment]
直接拉到最后，就是加个隐私声明？

**Comment by marcelowu** [comment]
https://wordpress.org/plugins/gdpr/
https://github.com/trewknowledge/GDPR
还有客户可以删除自己档案之类

**Comment by marcelowu** [comment]
![Captura de tela de 2020-12-06 10-01-17](https://user-images.githubusercontent.com/30912144/101280820-099a3080-37aa-11eb-98c5-1837bf63a4a0.png)

**Comment by dspurl** [comment]
应该就是用户可以注销账号，然后所有和该用户相关的信息都会清除吧，这应该针对网站的吧，项目中已经不用Cookie了
