### ISSUE TITLE
按照教程docker里面的nginx配置该怎么做？

### ISSUE THREAD

**Issue by LF-Wow** [dspurl/dsshop#69]
现在前置都完成了，迁移什么的都做好了，访问网址一直是404
![image](https://user-images.githubusercontent.com/21051872/100956281-1709ad80-3553-11eb-9314-cd9adeb31771.png)
![image](https://user-images.githubusercontent.com/21051872/100956336-34d71280-3553-11eb-87d7-6b6e099c3bcf.png)
还有个问题发现通过脚本创建的mysql容器，无法进入mysql，没有密码，这里的mysql是自己重启的一个

**Comment by FL-Dream** [comment]
已经解决了。是我不懂PHP配置的原因贴一下解决办法吧。
docker inspect  containerID  （可查看container内部IP以及port信息） 查看laradock_php-fpm_1在IP地址，填在下面的配置中
```
 server {
    listen 80;
    listen [::]:80;
    server_name 192.168.0.229; # 因为我这里是Ubuntu下的docker，所以填的是Ubuntu的地址，在局域网访问，本机随意
    root /var/www/laradock/dsshop/api/public;
    index index.php;
    include /etc/nginx/default.d/*.conf;
    location / {
                 index index.html index.htm index.php;
         }
        location ~ \.php$ {
            fastcgi_pass   172.19.0.6:9000; # 填laradock_php-fpm_1 的地址，默认端口9000
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
}
```
#### 还要一个问题，需要给storage文件夹777权限
```
chmod -R 777 /dsshop/api/storage
```

#### mysql容器问题
我通过手动运行mysql解决的密码问题，因为docker小白，没有root密码，面向百度编程也没找到进入mysql建库的方法，索性手动新建一个mysql容器，指定root密码

```
  docker run -d -it --name=laradock_mysql_1 -e MYSQL_ROOT_PASSWORD=zhang123 laradock_mysql
```

**Comment by dspurl** [comment]
了解下laradock和docker-compose，你会发现另一片天空
