### ISSUE TITLE
用宝塔可以部署么?

### ISSUE THREAD

**Issue by winsonlaw** [dspurl/dsshop#7]
可以用宝塔部署吗？我试了一直出错。，有教程吗？
、

**Comment by dspurl** [comment]
支持的，项目文档https://dspurl.github.io/dsshop/ 中有说明的，部署的时候就是推荐用宝塔的

**Comment by dspurl** [comment]
> 可以用宝塔部署吗？我试了一直出错。，有教程吗？
> ，


> 可以用宝塔部署吗？我试了一直出错。，有教程吗？
> ，
支持的，项目文档https://dspurl.github.io/dsshop/中有说明的，部署的时候就是推荐用宝塔的

**Comment by dspurl** [comment]
> 可以用宝塔部署吗？我试了一直出错。，有教程吗？
> ，
支持的，项目文档https://dspurl.github.io/dsshop/中有说明的，部署的时候就是推荐用宝塔的

**Comment by winsonlaw** [comment]
亲，你给的地址打不开(⊙o⊙)哦

**Comment by dspurl** [comment]
> 亲，你给的地址打不开（⊙o⊙）哦

https://dspurl.github.io/dsshop

**Comment by winsonlaw** [comment]
无法访问此网站dspurl.github.io 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by dspurl** [comment]
> 无法访问此网站dspurl.github.io拒绝了我们的连接请求。
> 请尝试以下方法：
> 
> 检查网络连接
> 检查代理服务器和
> 防火墙ERR_CONNECTION_REFUSED

你的网络不行，你直接这里把发现的问题截图下吧，然后我看下怎么帮你解决
