### ISSUE TITLE
小程序授权登录, 偶尔无法登录, 需要第二次点击

### ISSUE THREAD

**Issue by incasedo** [dspurl/dsshop#78]
/api/v1/app/authorizedPhone 报500错. 

问题应该和session_key不一致或者过期导致

错误代码如下:

EasyWeChat \ Kernel \ Exceptions \ DecryptException
The given payload is invalid.

EasyWeChat\Kernel\Exceptions\DecryptException: The given payload is invalid. in file /var/www/shop/api/vendor/overtrue/wechat/src/MiniProgram/Encryptor.php on line 41
Stack trace:
  1. EasyWeChat\Kernel\Exceptions\DecryptException-&gt;() /var/www/shop/api/vendor/overtrue/wechat/src/MiniProgram/Encryptor.php:41
  2. EasyWeChat\MiniProgram\Encryptor-&gt;decryptData() /var/www/shop/api/app/Models/v1/MiniProgram.php:187
  3. App\Models\v1\MiniProgram-&gt;miniWeixinPhoneNumber() /var/www/shop/api/app/Models/v1/MiniProgram.php:30
  4. App\Models\v1\MiniProgram-&gt;miniPhoneNumber() /var/www/shop/api/app/Http/Controllers/v1/Element/WeChatController.php:442
  5. App\Http\Controllers\v1\Element\WeChatController-&gt;authorizedPhone() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  6. call_user_func_array() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  7. Illuminate\Routing\Controller-&gt;callAction() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
  8. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239
  9. Illuminate\Routing\Route-&gt;runController() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/Route.php:196
 10. Illuminate\Routing\Route-&gt;run() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685
 11. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /var/www/shop/api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128
 12. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /var/www/shop/api/app/Http/Middleware/AppVerify.php:27

**Comment by incasedo** [comment]
已经解决

**Comment by dulihong** [comment]
请问楼主你的解决方法方便贴出来吗？谢谢。
