### ISSUE TITLE
可以指导一下为啥没有app.json，那我怎么在微信开发者中运行

### ISSUE THREAD

**Issue by xuyutong66** [dspurl/dsshop#88]

**Comment by dspurl** [comment]
这项目基于vue开发的，并不是微信小程序原生开发，需要了解uni-app，通过它能编译成小程序源码，再通过微信小程序展示的
https://uniapp.dcloud.io/quickstart

**Comment by xuyutong66** [comment]
谢谢，已解决

**Comment by xuyutong66** [comment]
再请教一个问题，我appid 填了，但是一运行请求这个接口api/v1/app/miniLogin就报错，这是代码中还需要配置什么吗
Request access_token fail: {"errcode":41002,"errmsg":"appid missing rid: 5fd32458-

**Comment by dspurl** [comment]
appid是微信小程序的，请求的接口是项目的，项目的需要配置`utils/config.js`

**Comment by xuyutong66** [comment]
utils/config.js文件加appid吗

**Comment by dspurl** [comment]
https://dswjcms_purl.gitee.io/dsshop/guide/getting-started.html#dsshop%E5%89%8D%E7%AB%AF%E4%BB%A3%E7%A0%81%E9%83%A8%E7%BD%B2-h5%E7%AB%AF%E3%80%81%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%AB%AF
先看一遍文档吧，虽然有出入，但看完基本知道如何使用了
